---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: imdb
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/west-wa-andrehe001-1001/imdb
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
