---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: heartbeat
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/bartr-devbox/heartbeat
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
