apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imdb
  namespace: imdb
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"

spec:
  tls:
  - secretName: imdb
    hosts:
    - 20.25.155.93
  rules:
  - host: 20.25.155.93
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: imdb
            port:
              number: 8080
